CHERIoT-Platform/cheriot-rtos

sdk/xmake.lua

Since the traversal order of lua's pairs is undefined, the order of the flags list will change randomly each time they are added.
xmake triggers a rebuild based on flags changes, which is not a problem if the list of flags is identical each time it is built.
Also, the xmake/dev branch has a fix for add_configfiles change detection, so that if you use the dev version, no rebuild will be triggered when the code has not changed, even if you switch release/debug mode.
You can run the following command to update to the dev version, which also adds support for ld.lld.
```
xmake update -s dev
```

Fix the problem of rebuilding all

---

scripts/devcontainer/Dockerfile

This reverts commit f0855be1f94843adb9f5ba18e2fbd6318708ace6.
It looks as if xmake's update command won't update the system-wide installation, which is probably a good idea in general (it shouldn't clobber the files owned by the package manager)

Revert "Update xmake to the latest version in the Dockerfile."

---

README.md
docs/GettingStarted.md
sdk/xmake.lua

Apparently execv supports it but runv does not.

Fix .dump generation

---

sdk/core/switcher/entry.S
tests/compartment_calls-test.cc
tests/compartment_calls.h
tests/compartment_calls_inner.cc
tests/compartment_calls_inner_with_handler.cc
tests/xmake.lua

The switcher does not check the validity of the target entry point. Add a check for that and implement a test.

Add a test for a bug in the switcher, alongside a fix

---

sdk/core/allocator/alloc.h
sdk/core/allocator/alloc_config.h
sdk/core/allocator/main.cc
sdk/core/allocator/revoker.h
sdk/include/ds/bits.h
sdk/include/ds/linked_list.h
sdk/include/ds/pointer.h
sdk/include/ds/ring_buffer.h
sdk/include/ds/xoroshiro.h
tests/allocator-test.cc

I hope that the include/ds files are the kinds of things that might be useful more generally for tiny, embedded systems. The goal here is to offer high-level abstractions without committing to bit-level representations, to some extent mechanizing the semantic gap between diagrams on paper and bit twiddling. I was not aware of an existing library, so I wrote my own; apologies if there's something I should have used instead.
There's still plenty of clean-up possible in the allocator.  In particular, IMHO, it'd be good to get some things on the alloc path more clearly communicating in terms of `MChunkHeader*` / `MChunk*` rather than `void *`s pointing just past the headers.

Turning the allocator into an overt exercise in data structure composition, part 1

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc

We used to set the shadow bit on malloc() and clear it on free() to guard against double free, but this is done by the load barrier anyway. The second free will have the tag cleared which will fail, so we don't have to do that.
Instead, to guard against the case of raising the base of an allocation to the top, which points to the shadow bit of the next header, which can either survive revocation or be used to trick the allocator into thinking it is a valid parameter for free(), we maintain the invariant that malloc headers must always point to shadow bits of 1, avoiding both problems.

Headers of heap chunks must point to set shadow bits

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
sdk/include/cheri.hh
tests/allocator-test.cc

We used to only check that cgetbase(mem) is correct. We harden free so that mem needs to be exactly equal to what the user got on malloc(). If there are missing permissions, different bounds and addresses, it is likely a bug from the user.
To implement this, a couple of things need to change:
1. The setbounds in malloc() needs at least capability alignment.
2. On malloc(size), if the returned chunk can be precisely covered by a capability, then always use the whole chunk.
3. If not, use the portion that can be precise, which shares the base with the whole chunk and is exactly MChunkAlignment smaller than the whole thing. If it is >= 2*MChunkAlignment smaller, then we must have split it into two chunks so this cannot happen.

Implement precise checking of free(mem)

---

examples/01.hello_world/xmake.lua
examples/02.hello_compartment/xmake.lua
examples/03.hello_safe_compartment/xmake.lua
examples/04.temporal_safety/xmake.lua
examples/06.producer-consumer/xmake.lua
examples/08.memory_safety/xmake.lua
examples/09.javascript/xmake.lua
sdk/core/allocator/main.cc
sdk/include/locks.hh
sdk/include/token.h
sdk/lib/atomic/README.md
sdk/lib/atomic/xmake.lua

The allocator initially ran with interrupts disabled. This allowed a slow allocation to prevent a realtime thread from making progress for quite a long time.  The new version ensures that the allocator is preemptible for almost all of its lifetime.
This does introduce a potential priority inheritance problem.  Consider three threads, A, B, C, in descending order of priority:
1. C begins freeing memory and is preempted
2. A begins allocating and blocks, waiting for C.
3. B runs without yielding.
Because B never yields, C is never scheduled and A is never able to make progress.  This can be fixed by adding a priority-propagating futex, which will be a future commit.

Use a lock to protect the allocator.

---

sdk/xmake.lua

Now that the linker generates something useful, enable the flag by default.

Generate the compartment report when linking.

---

sdk/software_revoker.ldscript

The old one worked but gave a confusing compartment report (some exports that were called didn't exist).

Fix the software revoker linker script.

---

docs/architecture.md
sdk/core/loader/boot.S
sdk/core/switcher/entry.S
sdk/core/switcher/tstack.h
sdk/include/cheri.hh

At present, our switcher calls our scheduler while in a "critical section" with `mscratchc` not actually pointing at the trusted save area.  The scheduler is not completely trusted and raising interrupts with `mscratchc` holding an arbitrary user capability seems like a great affordance for some weird machine that breaks everything we hold dear.
The changes here do two things:
- cosmetic changes to use `mtdc` instead of `mscratch` for the trusted save area.  No functional change intended, but it seemed like a good idea while in the neighborhood.
- substantive changes to use `mscratch` as a way of detecting reentrant exceptions.  I don't see a way to do this without two scratch registers, but maybe I'm missing something.
In any case, I took a stab at the problem and... it's not working and …

RISC-V reentrant exceptions handling

---

benchmarks/allocation/alloc.cc
benchmarks/timing.h
tests/test-runner.cc

On Sail, use minstret instead of mcycle, since it gives a useful number and mcycle does not.

Small fixes in timing output.

---

sdk/core/loader/boot.cc
sdk/core/switcher/entry.S

Zeroing the stack is a huge part of the total cost of cross-compartment calls.  Running on Sail (reporting retired instructions), the compartment-switcher benchmark (from #37) reports (stack size, call+return, call, return):
0x100   213     127     86
0x200   405     223     182
0x400   789     415     374
0x800   1557    799     758
0x1000  3093    1567    1526
If we skip stack zeroing, the numbers are 95, 67, 28 for all of them. This means that, even with tiny stacks, zeroing is more than half of the cost of a compartment switch and that cost grows with larger compartments.
We currently require three instructions per store in the zeroing loop. This commit unrolls the loop so that we zero 32 bytes at a time.  The results are now:
0x100   185     113     72
0x200   313     177     136 …

Unroll the zeroing loop

---

sdk/include/compartment-macros.h
sdk/include/multiwaiter.h
sdk/include/stdlib.h
sdk/include/token.h
tests/allocator-test.cc
tests/static_sealing-test.cc

Updating the demo found a few places where C compatibility was not quite right.  In particular, C doesn't merge compatible definitions, which causes a lot of pain with the static sealing type macros.

Improve C compatibility.

---

sdk/core/scheduler/common.h
sdk/core/scheduler/main.cc
sdk/core/scheduler/thread.h
sdk/include/debug.hh
sdk/include/riscvreg.h
sdk/include/thread.h
sdk/xmake.lua

These are guarded behind a flag enabled in the build system and the scheduler doesn't track them if they are not enabled.
Since it's unhelpful to be able to get 64-bit numbers and not log them for debugging, the `ConditionalDebug::log` mechanism can now log unsigned 64-bit values as hex.  Logging them as decimal requires a 64-bit divide, so that's not done yet (as hex the two 32-bit halves can simply be printed separately, high then low).

Add (optional) scheduler APIs for reporting the time.

---

sdk/core/loader/defines.h
sdk/core/switcher/trusted-stack-assembly.h
sdk/core/switcher/tstack.h

Prior to this a TrustedStackFrame was 56 bytes.
This was a problem because it meant that the size of the trusted stack was not always a multiple of 16 bytes (depending on whether there were an odd or even number of frames). If the trusted stack size is not a multiple of 16-bytes the loader would round it up which confused the overflow check in the switcher and could lead to an unexpected trap which would leak capabilities.
This change adds an extra 8 bytes of padding to TrustedStackSize to ensure it is a multiple of 16-bytes.
We also add two static asserts to check this.

Ensure the trusted stack stack size is a multiple of 16-bytes.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/revoker.h

This should never be used in production but helps provide a baseline for the cost of various hardware features.

Fix the no-temporal-safety mode.

---

sdk/core/allocator/alloc.h
sdk/include/debug.hh

Some of the asserts depended on `volatile` loads and stores and so were still (partially) compiled in.  The cost of these for 32-byte allocations was roughly equal to the cost of shadow bit manipulation, so had a significant impact on the benchmarks.

Fix asserts to not run in releases.

---

sdk/core/scheduler/main.cc
sdk/core/scheduler/thread.h
sdk/include/thread.h
tests/thread_pool-test.cc

This might be useful for TLS abstractions and will be necessary for priority-inheriting futexes.

Add a fast accessor for the thread ID.

---

compile_flags.txt
sdk/boards/flute-debug-uart.json
sdk/boards/flute-software-revoker.json
sdk/boards/flute.json
sdk/core/allocator/revoker.h
sdk/xmake.lua

Board descriptions can now provide a set of paths for SoC-specific includes.  These are ordered, so `#include_next` can work to provide customisations if necessary.
This is now used for the Flute hardware revoker (which is a prototype) and should make it easy to support the recently added Ibex revoker.
The same interface should be used for interrupt controllers, which are currently somewhat tangled with the scheduler but that's follow-on work.

Start providing some sensible driver interfaces.

---

sdk/core/loader/boot.cc

This ensures that we have a valid tagged capability that spans the regions that must be scanned.  We may also scan some regions that cannot contain revocable capabilities.
Fixes #76

Use imprecise setbounds for the software revoker's regions.

---

sdk/core/loader/boot.cc
sdk/firmware.ldscript.in

We were always aligning the heap to a 512-byte boundary.  This works on 256 KiB platforms (though is too aggressive if > 50% of the memory is used for code and globals) and works 50% of the time on 512-byte platforms.  Do the rounding in the loader so that it can be based on the total size.
Fixes #75

Round the heap region in the loader.

---

sdk/core/scheduler/thread.h
sdk/include/locks.hh
sdk/include/ring_buffer.hh
sdk/lib/thread_pool/thread_pool.cc

This allows the thread pool to remove the scheduler from its TCB for confidentiality and integrity.
This exposes (and then fixes) a big in the thread list walking code.

Add a ring buffer and move the thread pool to using it.

---

sdk/core/scheduler/main.cc
sdk/include/c++-config/cheriot-atomic.hh
sdk/include/futex.h
sdk/include/locks.hh
sdk/include/ring_buffer.hh
tests/locks-test.cc
tests/xmake.lua

Eventually we will move to using one from libc++, but the layering in these is difficult to support without bringing in all of the threading code.  In the interim, clang generates much better code if you use the sized builtins directly rather than relying on `_Atomic` (in particular, it generates called to sized versions rather than a random mixture of sized and unsized versions), so it's convenient to have something that wraps these.
The implementation is intended such that it can later be replaced with:
```c++
namespace cheriot
{
template<typename T>
using atomic = std::atomic<T>;
}
```
In the interim, placing it in a separate namespace should provide a hint that it isn't a complete implementation.

Add an almost-standards-compliant atomics implementation.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
sdk/include/stdlib.h
tests/allocator-test.cc

This makes it possible to claim a heap allocation so that it counts towards your quota (in addition to any other claims and the original owner's quota) and cannot be freed until everyone relinquishes their claims.
Claims can also apply to sub-objects and claim the entire object.
`heap_free` is a unified point for freeing and dropping claims.  This allows freeing heap pointers without worrying about who originally allocated them.

Add a claims API to the allocator.

---

.github/workflows/main.yml
docs/BoardDescriptions.md
scripts/run-flute.sh
sdk/boards/flute-debug-uart.json
sdk/boards/flute-no-revoker.json
sdk/boards/flute.json
sdk/boards/sail.json
sdk/xmake.lua

This extends the board description file to be able to find the location of a simulator.
This also includes a script to convert ELF files to the hex dumps that Flute requires and to invoke the Flute simulator.
This also adds the missing flute config, for running benchmarks with the revoker disabled.

Add support for `xmake run`.

---

.devcontainer/devcontainer.json

When creating a new github codespace the postAttachCommand from the devcontainer.json was not being run automatically. This might be because onCreateCommand is more appropriate.

Attempt to fix problem with command run in dev container.

---

compile_flags.txt
sdk/core/loader/boot.S
sdk/core/loader/boot.cc
sdk/core/loader/constants.h
sdk/core/loader/types.h
sdk/core/scheduler/common.h
sdk/core/scheduler/main.cc
sdk/firmware.ldscript.in
sdk/xmake.lua

The loader was initialising threads given two (fairly complex) macros passed via `-D` at compile time.  This caused two problems for auditing:
- The loader .o files were different depending on thread configuration.
- The description of threads was interleaved in the loader and hard to separate.
In the new structure, the unlinked loader binaries should be identical for all firmware images.  After linking, they will embed the address of the image header (which should make the hashes of the linked version predictable by anyone who has a copy of the unlinked binary).  All of the thread information now lives in the .thread_config section and so is amenable to being added to the linker report (not done yet).
This also removes the bump allocator from the loader.  This caused some problems with …

Remove thread macros from the loader.

---

benchmarks/compartment-call/callee.cc
benchmarks/compartment-call/callee.h
benchmarks/compartment-call/caller.cc

Due to the way the call and return costs for this benchmark were computed they didn't always add up to the total for the full call. We can eliminate this inconsistency by recording the start and end times on either side of the call and having the call return the time in the middle and computing the call and return times from this. The result is much simpler, sure to be self-consistent and the result for the full call is the same as before (at least on Sail) because reading the cycle counter simply takes the place of an instruction that otherwise placed zero into a0 for the 'noop' call.

Simplify compartment-call benchmark and make it more self consistent.

---

sdk/xmake.lua

The compartment switcher will not behave correctly if subsetting a stack results in something unrepresentable.  We can avoid this by limiting stacks to the maximum representable size for 16-byte alignment.
Eventually this can be removed if we make the switcher round the shared bit of the stack down to avoid overlap.  At the moment, it's not a serious limitation because our stacks are very rarely over 1 KiB and the limit is about 8 KiB.
Fixes #58

Enforce stack-size limit.

---

sdk/include/errno.h

Also renumber everything so that this doesn't conflict.
We use -1 to indicate that a compartment has crashed because -1 is an easy constant to generate.

Add an errno value for compartment failure.

---

sdk/core/allocator/main.cc
sdk/include/stdlib.h
tests/allocator-test.cc

This API takes a heap capability and frees *all* memory that can be freed by that capability.
The current implementation holds the heap lock for the entire heap walk. This may not be ideal but it's somewhat complex to avoid.  We would need to ensure that the chunk that we are currently inspecting is not coalesced when we yield.

Add `heap_free_all`.

---

docs/BoardDescriptions.md
docs/Interrupts.md
sdk/core/scheduler/plic.h
sdk/xmake.lua

These are automatically completed in the scheduler and so do not require explicit completion.

Add support for edge-triggered interrupts.

---

sdk/core/allocator/main.cc
sdk/core/scheduler/main.cc
sdk/core/scheduler/thread.h
sdk/include/c++-config/cheriot-atomic.hh
sdk/include/futex.h
sdk/include/locks.hh
sdk/include/ring_buffer.hh
sdk/include/thread.h
tests/allocator-test.cc
tests/futex-test.cc
tests/locks-test.cc
tests/xmake.lua

Each thread now has its static priority and the priority that it is boosted to.  The futex wait operation now takes some flags, one of which is for priority inheriting futexes.  If this is used then the futex word is expected to contain the thread ID of the lock owner in the low 16 bits (similar to the Linux PI futex model).  That thread will then inherit the priority of the caller of futex wait, for the duration of the wait (when the wait returns, the priority of the interrupted thread is restored).
This also adds a number of tests, introduces a priority inheriting flag lock, and makes the allocator use it.
This fixes the issue that a low-priority thread that is preempted in the allocator can prevent higher-priority threads from being able to make progress.

Add support for priority inheritance.

---

scripts/build_benchmark_configs.sh
sdk/core/allocator/revoker.h
sdk/xmake.lua

This takes a base board.json, modifies it to include the different variations, then builds the specified benchmark, once for each version.
Also fixes some bugs for configurations we haven't tested.

Add a script for building all of the configurations of a benchmark.

---

.devcontainer/devcontainer.json

The old dev container was built by an Azure Pipelines job backed by an Azure Scale Set.  Unfortunately, Azure Scale Sets don't allow you to replace the VM image and the Ubuntu one that we were using went away.  Since I have left Microsoft, there are no people who both know how to fix this problem and have the required access.
I have set up public CI with Cirrus-CI.  This now does pre-merge testing for LLVM and also builds container images for both x86-64 and AArch64.  This PR updates the devcontainer path to point to that image.  It also fixes an error pointed out by VS Code in the location of settings for the devcontainer.

Update the devcontainer location.

---

sdk/core/loader/boot.cc
sdk/xmake.lua

These were the wrong way around in the xmake.

Fix the size of the loader's stack and trusted stack.

---

sdk/core/loader/boot.cc
sdk/core/loader/constants.h
sdk/core/loader/types.h
sdk/core/switcher/entry.S
sdk/firmware.ldscript.in
sdk/library.ldscript
sdk/xmake.lua

This contains two commits.  The first makes the switcher entry point a real export.  This is a starting point for adding other exports from the switcher (for example, debugging facilities to get a compartment stack trace or to query the amount of trusted stack depth available).
The second moves library export tables (including the switcher ones) to the heap region, since they're not needed after loading.
This will fail in CI until CHERIoT-Platform/llvm-project#3 is merged.

Clean up library exports

---

.github/workflows/main.yml
scripts/run-ibex-safe-sim.sh
sdk/boards/ibex-safe-simulator.json
sdk/core/scheduler/main.cc
sdk/include/platform/generic-riscv/platform-timer.hh
sdk/include/platform/generic-riscv/platform-uart.hh
sdk/include/platform/ibex/platform-hardware_revoker.hh

This adds the board description and a script for running firmware images.  It's now possible to target the Ibex simulator with `--board=ibex-safe-simulator` and then run with `xmake run`.
This includes a few other changes:
- In simulation environments, don't poll for the UART to be ready to write.  It always is and removing the loop speeds up output a *lot*.
- The Ibex simulator does not support the tohost magic (this is hard to support in any simulator that doesn't read ELF files) and exits by writing a byte with the top bit set to the UART.  In `simulation_exit`, we try that after the write to the tohost
- The Ibex doesn't have a full CLINT, only the registers that we use. Rather than providing a separate CLIT driver, there's now an ifdef for choosing the locations of the two …

Add support for the Ibex in the SAFE configuration.

---

docs/GettingStarted.md

First is a minor fix of directory name from `llvm` to `cheriot-llvm`.
Second is some fixes to the `cmake` command:
- `${LLVM_PATH}` needs to be followed by `llvm` to find the correct folder.
- Remove some extra spaces in the command argumetns.
- Remove `LLVM_ENABLE_LLD` to resolve the following error on GCC
platforms:
```
CMake Error at cmake/modules/HandleLLVMOptions.cmake:298 (message):
Host compiler does not support '-fuse-ld=lld'
```

Update LLVM build instructions

---

exercises/01.compartmentalisation/README.md

Attempt to clarify some things, fix a typo and incomplete sentence. Also add instructions to configure before attempting to build.

Exercise 1 readme tweaks

---

exercises/01.compartmentalisation/load_js.sh
exercises/01.compartmentalisation/microvium-ffi.hh

This got lost in some accidental rebasing.  This allows the automatic FFI wrappers to work with both local and cross-compartment function calls.

Fix FFI wrapper in exercise.

---

exercises/01.compartmentalisation/load_js.sh

If you don't, apt will use stale indexes and then fail in the installation because the package repo state doesn't match what it expects.

Run apt-update before installing things.

---

scripts/ibex-build-firmware.sh
scripts/run-ibex-safe-sim.sh
sdk/boards/ibex-arty-a7-100.json
sdk/include/platform/arty-a7/platform-gpio.hh
sdk/include/platform/generic-riscv/platform-uart.hh
sdk/include/platform/synopsis/platform-uart.hh

This is the CHERIoT SAFE platform in the Arty A7 100 FPGA.
- Adds a board description file.
- Separates out the script to generate the hex file from the one to run the simulator.
- Adds a driver for the GPIO LEDs.  This will change soon because Kunyan is going to change the wiring a bit, but people can play with it now.
- Improve the generic UART driver slightly.
- Add a driver for the Synopsis extended version of the 16550 with a divisor that supports higher frequencies.
This is sufficient to build firmware that can be loaded in the Ibex-based CHERIoT-SAFE configuration.  The resulting vhx file can be either added to the bitfile or loaded over the UART if the IROM is configured with:
https://github.com/CHERIoT-Platform/cheriot-safe-uart-boot-rom

Add a platform description for the A7.

---

sdk/core/allocator/main.cc
sdk/core/loader/boot.S
sdk/core/loader/boot.cc
sdk/core/loader/types.h
sdk/include/compartment-macros.h
tests/mmio-test.cc
tests/test-runner.cc
tests/tests.hh
tests/xmake.lua

This is most useful for read-only access, but the mechanism should be sufficiently general to permit other uses (in particular, once we have CHERI-aware devices, it may be useful to restrict the ability to store capabilities and the ability to load mutable capabilities from devices).

Add support for importing MMIO capabilities reduced permissions.

---

sdk/core/allocator/alloc.h
sdk/core/loader/boot.cc
sdk/core/scheduler/main.cc
sdk/core/scheduler/thread.h
sdk/core/switcher/entry.S
sdk/core/switcher/trusted-stack-assembly.h
sdk/core/switcher/tstack.h
sdk/include/event.h
sdk/include/locks.h
sdk/include/locks.hh
sdk/include/thread.h
sdk/lib/event_group/event_group.cc
sdk/lib/locks/locks.cc
tests/eventgroup-test.cc
tests/futex-test.cc
tests/queue-test.cc
tests/thread_pool-test.cc

This is reading a single value per thread, which never changes, and so adds only three instructions (including cret) to the switcher.  We previously had two ways of getting the thread ID:
- thread_id_get() returned the ID, but required a full compartment switch into the scheduler.
- thread_id_get_pointer() retrieved a cacheable pointer that could be dereferenced to give the current thread ID.
The latter form was fast, but could not be used in shared libraries because it required capturing the returned pointer.
This simplifies the locks APIs and means that the message-queue compartment can be entirely stateless (no mutable globals) and so a compromise cannot persist.

Move thread_id_get() into the switcher.

---

sdk/core/scheduler/main.cc
sdk/lib/locks/locks.cc
tests/allocator-test.cc
tests/futex-test.cc
tests/locks-test.cc

Various fixes related to logging in three separate commits:
1) Fix OOB access in scheduler, add a test and some logging.
2) Fix unnecessary wait failures and spurious notifies in `InternalFlagLock::try_lock`
3) Actually run the recursive mutex test and make it pass.

Lock fixes

---

sdk/include/compartment-macros.h
sdk/include/debug.hh
sdk/include/stdatomic.h
sdk/include/string.h
sdk/lib/string/strchr.c
sdk/lib/string/xmake.lua

Most of these are fixes for either:
- Macros that we don't test using don't actually work in C code.
- C headers contain things that don't work if you include them in more than one compilation unit.
At the same time, add explicit overloads for printing uint16_t / uint32_t.  Without this, integer promotion promotes them to int and we print them as signed (decimal) numbers, not as hex.

Fixes to C headers and debug output.

---

sdk/include/fail-simulator-on-error.h

The fail-on-simulator-error error handler is useful for debugging, but without the PCC that caused the crash it's somewhat less useful.

Make the error messages more helpful.

---

sdk/include/thread.h

We didn't have generic functions for spinning / sleeping and they're quite important.

Expose sleep-wait functions.

---

compile_flags.txt
sdk/boards/ibex-arty-a7-100.json
sdk/include/platform/arty-a7/platform-ethernet.hh
sdk/include/platform/concepts/ethernet.hh

This includes a driver for Kunyan's ethernet adaptor.

Add ethernet bits to Arty A7 board description.

---

sdk/include/FreeRTOS-Compat/event_groups.h
sdk/include/FreeRTOS-Compat/queue.h
sdk/include/event.h
sdk/lib/event_group/event_group.cc

- The order of clear-on-exit and wait-for-all flags was incorrect in the event-wait function.
- Make sure that we can kick all waiters out of a sleep state when we delete an event group.
- Make the queue error values match the macros that calling code compares them against.

Small fixes to the FreeRTOS compat layer:

---

sdk/boards/ibex-arty-a7-100.json
sdk/include/platform/arty-a7/platform-ethernet.hh

- Now runs at 33 MHz (yay Kunyan!)
- Ethernet is now on the fast side of the memory bridge (additional yay Kunyan!)

Update the Arty A7 build config:

---

sdk/include/string.h
sdk/lib/string/strlcpy.c
sdk/lib/string/xmake.lua

We have a strcpy implementation that wraps strncpy, so we end up trying to pad 4 GiBs of zeroes.

Do not zero-pad in strncpy.

---

sdk/include/compartment-macros.h
tests/static_sealing-test.cc

The test and malloc-capability macros were inconsistent in how they expected these to be use:
- The test wanted to pass all arguments in braces.
- The malloc macro wanted to pass them as separate arguments.
The implementation expected the former, but broke when you actually tried to pass multiple values.  This happened to work with malloc capabilities because we were zero-initialising the subsequent fields and so ignoring the explicit zeroes was fine.
This is now fixed to use a variadic macro (hopefully) correctly.

Fix defining static sealing values with structures.

---

tests/stack-test.cc

We rely on the test detecting a failure with an odd number of trusted stack frames.  The latest compiler changes allow the compiler to directly call (or even inline) calls to CHERI callbacks if they are in the same compartment as the caller.
This adds a call via a volatile function pointer, which the compiler is not permitted to elide.

Make the tests more robust in the presence of compiler changes.

---

scripts/run_clang_tidy_format.sh
sdk/lib/crt/arith64.c
sdk/lib/crt/xmake.lua

With the new compiler changes (CHERIoT-Platform/llvm-project#11,) we can now properly emit cross-library calls for builtins that are inserted late in compilation.  This means that (among other things) `a / b` as 64-bit integers can be lowered to cross-library calls for 64-bit arithmetic.  We now need to have implementations of these.
Fortunately, there's a permissively licensed C implementation that required minimal adaptation.

Add 64-bit arithmetic helpers.

---

sdk/include/ds/xoroshiro.h
sdk/include/platform/arty-a7/platform-entropy.hh
sdk/include/platform/concepts/entropy.h

The Ibex / Arty A7 uses the cycle count and the number of Ethernet interrupts to seed.  The first of these starts counting when the first-stage (ROM) loader runs and so depends on the speed at which we load the firmware over the UART, the second after the scheduler starts and depends on external network traffic.  These are not even slightly cryptographically secure, but they do provide enough entropy that we get different values from the PRNG across different runs and so can pretend for the purpose of a prototyping platform.

Add a concept for a platform entropy source and a weak implementation.

---

sdk/compartment.ldscript
sdk/include/compartment-macros-asm.S
sdk/library.ldscript
sdk/xmake.lua

This is essential for BearSSL, which wants to compile everything but then throw away all of the things that are not referenced by your specific use case.  It's nice to have for everything else.  It reduces the size of the FreeRTOS network stack by around 7.5%.
Savings in the test suite are very small (around 1%) and mostly come from some functions in headers that should be `inline` and aren't.

Enable linker dead-code elimination.

---

sdk/include/fail-simulator-on-error.h

CHERIoT Ibex now has the correct exception priorities.

Remove work-around for Ibex bug.

---

docs/GettingStarted.md
scripts/ibex-build-firmware.sh

This PR addresses two issues when onboarding with the Arty A7:
- The `ibex-build-firmware.sh` script has a bug that makes it fail when a directory is not manually created
- There is no documentation on how to load the firmware onto the FPGA

Smoothen onboarding with Arty A7

---

sdk/include/futex.h
sdk/include/locks.h
sdk/include/locks.hh
sdk/lib/locks/locks.cc
tests/locks-test.cc

This PR contains three commits:
- First one fixes some stale comments which I found somewhat confusing
- Second one implements lock destruction (see issue #168)
- Last one does some cleanup in the locking tests for coherence and consistency
It would be nice to implement `test_destruct_flag_lock_acquire` with templating, unfortunately we are hitting a compiler bug which prevents us from doing that. Let's add templating to that function once the compiler bug is reported and fixed.

Implement lock destruction feature + cleanup in locking-related code

---

sdk/lib/locks/locks.cc
sdk/lib/locks/xmake.lua
tests/locks-test.cc

This PR contributes:
- Bug fixing for an overflow bug in ticket locks
- Add asserts to catch potential bugs in the locking subsystem
- Expose debugging options for the locking subsystem through the build system

Bug fixing and asserts in the locking subsystem

---

scripts/ibex-build-firmware.sh
scripts/includes/helper_find_llvm_install.sh
scripts/output_code_size.sh

We need a standard and common way of measuring firmware images sizes to optimize this metric.
Add a helper script to `scripts/` to measure this.
Re-use the LLVM tool finding bit of the Ibex script by factoring it out in its own file.

Add a script to measure firmware image sizes

---

docs/GettingStarted.md

We need objcopy for the bootloader:
https://github.com/CHERIoT-Platform/cheriot-safe-uart-boot-rom/blob/92e9673ab2c65a621e6e3411d14d21275dcab5a1/Makefile#L4
I found how to do this in this file:
https://github.com/CHERIoT-Platform/llvm-project/blob/dfbd2b1fdd33746ca9e615feb7852013e8f3966a/.cirrus.yml#L49

Add objcopy to LLVM build instructions

---

sdk/include/cheri.hh
sdk/lib/queue/queue.cc
tests/check_pointer-test.cc
tests/static_sealing_inner.cc
tests/test-runner.cc
tests/tests.hh
tests/xmake.lua

This PR adds a new strict mode to `CHERI::check_pointer` which can be enabled by setting the `EnforceStrictPermissions` templating argument to `true`.
In this mode, `check_pointer` removes permissions which are not declared in `Permissions` from the passed `ptr` reference, and adjusts its bounds to match `space`.
This is useful for detecting cases where compartments ask for less permissions than they actually require.
Extend the test suite to test this new feature.

Add strict permissions and bounds mode to `CHERI::check_pointer`

---

sdk/include/assembly-helpers.s

This now works like AUIPCC, from a relocations perspective, but the linker still accepts the old format.  This updates the assembly to not require the compat paths (we'll keep them for a while though).

Update LoadCapCGP assembly.

---

sdk/core/allocator/main.cc
sdk/core/scheduler/main.cc
sdk/include/cheri.h
sdk/lib/compartment_helpers/check_pointer.cc
sdk/lib/queue/queue_compartment.cc

This is the code that was in the allocator, generalised for other uses. Factoring this out should reduce code size and ensure that a consistent check is applied everywhere (a weaker check would break if passed into the allocator, for example).
Note: This increases the size of the test suite by 8 bytes, but only because it also fixes a missing check.

Add a helper for checking timeouts.

---

examples/02.hello_compartment/README.md
examples/02.hello_compartment/hello.cc
examples/02.hello_compartment/policy.rego

This checks that we've actually achieved the compartmentalisation goal that we said we wanted to.  Spoiler: The previous version did not, and so now is fixed.

Add a policy to example 2.

---

sdk/include/timeout.h
tests/misc-test.cc
tests/test-runner.cc
tests/tests.hh
tests/xmake.lua

Currently unlimited timeouts are not really unlimited, because we still do the substraction in `elapse`. Fix this by only doing the substraction when remaining is not `UnlimitedTimeout`.
While at it, improve the documentation, and add a test.

Fix unlimited timeouts.

---

sdk/core/allocator/main.cc
sdk/include/token.h
tests/allocator-test.cc

This mirrors heap_can_free, but works on a sealed objects.
This is useful for APIs like the TLS stack where there's some teardown necessary before freeing and if the free happens at the end then we've accidentally authorised something that we shouldn't.

Add token_obj_can_destroy API.

---

sdk/core/loader/boot.cc
sdk/core/loader/types.h

This addresses the 'shouldn't silently fail' part of #182.  A subsequent change may allow it to also work, depending on use cases.

Add a check that the unused bits in MMIO imports are unused.

---

sdk/include/string.h
sdk/lib/string/memchr.c
sdk/lib/string/strchr.c
sdk/lib/string/xmake.lua
tests/misc-test.cc

This is small and necessary to have `std::string_view::find`, which is useful, among others, for validation of input in the network stack.
Add a small test for the implementation.

Add `memchr` to the standard library.

---

docs/GettingStarted.md

This went away when we moved the sail-riscv submodule to the CHERIoT-Platform org.
Reported by @gavinhoward

Remove reference to the patch_sail_riscv target.

---

sdk/core/switcher/entry.S

Now that the stack high water mark is explicilty 16-byte aligned we no longer need to mask it in the switcher.
See https://github.com/microsoft/cheriot-sail/pull/49
This PR is likely to fail CI until the dev container is rebuilt with the above Sail changes.

Remove redundant mask of stack high water mark in switcher.

---

sdk/include/platform/arty-a7/platform-ethernet.hh

Although the frame pointer and its length are supplied by the firewall which is trusted, the firewall does not check the pointer which is coming from external untrusted components. We must therefore check it.

Add frame buffer pointer check to Arty A7 Ethernet driver.

---

sdk/include/platform/arty-a7/platform-entropy.hh

Two reasons why we likely want this:
- If we don't fetch it every time, we will permute with the same number every time, which isn't great in terms of entropy. The runtime cost shouldn't matter because we're not calling reseed often at all.
- This makes us win 8 Bytes per entropy source.

Fetch ethernet receive interrupt entropy at every reseed.

---

sdk/include/fail-simulator-on-error.h

`get_register_value` returns a nullptr when passed CZR, causing a crash in the error handler. We need to treat CZR as a special case.

Fix `fail-simulator-on-error` handler issue with nullptr dereferences.

---

sdk/include/platform/arty-a7/platform-ethernet.hh
sdk/include/platform/concepts/ethernet.hh

With a single FPGA on a network it was fine to have a single random MAC. With two, we need to be able to determine whether to just use the device's one or generate a random one.

Expose the fact that the MAC is not unique.

---

.gitmodules

This was added accidentally and is not used.

Remove freertos-plus-tcp submodule.

---

.github/workflows/main.yml
sdk/core/allocator/alloc_config.h
sdk/core/allocator/main.cc
sdk/core/switcher/entry.S
sdk/include/cdefs.h
sdk/include/debug.hh
sdk/include/switcher.h
sdk/xmake.lua
tests/allocator-test.cc

This makes it possible to dynamically check the maximum stack usage for a compartment entry point in testing.  This is intended to be used in conjunction with CHERIoT-Platform/llvm-project#22, which makes it possible to specify the minimum stack size (enforced by the switcher).

Add APIs for checking stack usage.

---

sdk/include/locks.h
sdk/lib/locks/locks.cc
tests/locks-test.cc

The ability to upgrade for destruction without holding the lock is useful for cleaning up from the error handler.
Add various tests to detect regressions in the `unlock` function.

Make it possible to upgrade a lock for destruction without holding it.

---

sdk/include/queue.h
sdk/lib/queue/queue.cc
tests/queue-test.cc

This new API destroys a queue, waking up all threads waiting to produce or consume, and making them fail to acquire the lock, before deallocating the underlying allocation.
This requires to add a destruction mode to the high bits lock class.
This is particularly useful when destroying a message queue from an error handler.

Add a `queue_destroy` API.

---

sdk/include/event.h
sdk/lib/event_group/event_group.cc

This new API destroys an event group without tacking the lock.
This API is inherently racy. Its main purpose is to cleanup the event group in an error handler context, when taking lock may be impossible.
While we are at it, all `eventgroup_destroy` operations, forced or not, should upgrade the lock for destruction before freeing it.
We could also add a `force` parameter to the existing `eventgroup_destroy` API, however we would need to go and edit all callers since this is a C API.

Add a `eventgroup_destroy_force` API.

---

sdk/include/locks.hh

This new `release` API unwraps the lock without unlocking it. This is useful to call before destroying a lock.

Add a `release` API to `LockGuard`.

---

sdk/core/loader/boot.cc

This assertion should have fired previously when we introduced the hazard pointer region for `heap_claim_fast` but it did not because we have devices before and after main SRAM.  On targets where this is not the case, it fires spuriously.

Fix an assertion in the loader.

---

sdk/include/FreeRTOS-Compat/queue.h
tests/queue-test.cc

Our allocation size only covers the first field of `QueueHandle_t` (`struct QueueHandle`), and the `void * freePointer` is out of bounds. This may be due to unfortunate naming of the two data types - I would typically expect `QueueHandle_t` to be an alias for `struct QueueHandle` but that is not the case here.
Unfortunately this has not been detected earlier because the Arty board (unlike the Ibex simulator) does not seem to trigger a tag violation. This will be investigated separately.
For now, add a test that highlights the bug in the Ibex simulator, and fix the bug. The test is intentionally left very simple, we can extend later on if needed.

Fix buffer overflow in the FreeRTOS compat queue

---

sdk/include/thread.h

An overflow in the `thread_millisecond_wait` was likely with 30MHz clocks.
There's an additional commit that removes debug messages and adds semicolons to the end of `__if_cxx` which produces slightly nicer results out of clang-format.

Fixed overflows in wait functions

---

sdk/include/stdlib.h

Currently `malloc` blocks indefinitely when it cannot perform an allocation. This deviates from the usual behavior of `malloc`, which would return a NULL pointer and may set `errno`, but not block indefinitely, when an allocation cannot be performed.
Set the timeout to 0 to immediately return when an allocation cannot be satisfied.

stdlib `malloc` should not block indefinitely.

---

sdk/core/switcher/entry.S
sdk/include/errno.h
tests/stack-test.cc
tests/stack_integrity_thread.cc
tests/stack_tests.h
tests/test-runner.cc

The ABI has included space for the required stack space from the start, but we only recently started putting anything sensible there.  It turns out that the switcher was missing this check.
This introduces a new errno code to let the caller differentiate between a call that wasn't allowed to proceed and one that crashed.  We may want to use this code for other stack badness.

Add missing stack check.

---

benchmarks/allocation/alloc.cc
docs/Allocator.md
sdk/core/allocator/main.cc
sdk/core/scheduler/common.h
sdk/core/scheduler/multiwait.h
sdk/include/microvium/microvium_port.h
sdk/include/stdlib.h
sdk/lib/event_group/event_group.cc
sdk/lib/queue/queue_compartment.cc
tests/allocator-test.cc
tests/queue-test.cc

We have recently introduced strong stack size requirements in the allocator (https://github.com/microsoft/cheriot-rtos/pull/205). Following this, `-ECOMPARTMENTFAIL` is returned not only when the allocator compartment crashes, but also at compartment entry when the stack is insufficient to proceed safely.
Entering a state where the stack is not sufficient to call the allocator is not unrealistic given that we are running with very small stacks. We need to handle it well.
Unfortunately this behavior has not yet been documented, and the code has not been adapted to it. Nearly the entire core repository still does `NULL` pointer checks to check the return value of a memory allocation.
This commit documents this new behavior at appropriate places and fixes allocator call sites to ensure that …

Various fixes related to memory allocator error handling

---

sdk/core/loader/boot.S

This cjalr cra is in some code that is first hit after a cjal and so the cjalr cra returns.  The caller then discards the value written back to cra as the link operation in the jump-and-link instruction.  It is then used as a call, with cra initialised to a jump address.
This was done as a code-size optimisation, but there's actually no need to zero the registers at the start.  The code that runs with the (possibly uninitialised) values in registers (most implementations will zero in boot ROM or hardware anyway) all runs with access to the primordial capabilities and so there is no way that this can possibly leak information.
The first untrusted code runs after the *second* pass through this block.
Simply removing this should shave 10 bytes off the loader without affecting security.  More …

Remove the exciting jump instruction from boot.S

---

sdk/core/allocator/token.h
sdk/include/__debug.h
sdk/include/__macro_map.h
sdk/include/debug.h
sdk/include/debug.hh
sdk/lib/debug/debug.cc
tests/debug-test.c
tests/debug-test.cc
tests/test-runner.cc
tests/tests.hh
tests/xmake.lua

These refactor the C++ bits slightly so that the library functions are safe to use from C or C++ (without defining identifiers called things like Bool in the global namespace) and provides some debug macros that can be used from both C and C++, so that they can be used in headers.
As with the C++ versions, these use {} as the placeholders (no format specifiers supported yet) and pass the type along with the value as an argument.

Add type-safe debugging macros for C.

---

sdk/lib/event_group/event_group.cc

Notifying waiters is not enough, we need to ensure that they get appropriate bits to leave the loop.

Set appropriate bits in `eventgroup_destroy_force`.

---

examples/04.temporal_safety/README.md
examples/08.memory_safety/README.md

Fix small typos in two of the README files in examples
closes #231

fix typos in examples READMEs

---

sdk/boards/sonata.json

There is now a bootloader on that sonata platform that loads software to 0x00101000.

Changed the Sonata instruction memory start

---

scripts/run-sonata.sh
sdk/boards/sonata.json

The latest (v0.2.0 or later) Sonata RPi firmware can load a UF2 file from the USB flash device, eliminating the need for any loader tooling installed on the host.
This adds a script that:
- Builds the UF2 image
- Tries to determine where the Sonata board's filesystem is mounted
- Copies it there if it can
- Tells you where the file is and asks you to copy it manually if not.

Add a working `xmake run` command for Sonata.

---

sdk/boards/sonata.json

For some reason, this was not enabled in the Sonata board config. Enabling it improves the test suite performance by around 5%.

Sonata has the stack high-water mark register.

---

tests/ccompile-freertos-test.c

We have had the build infrastructure for testing that the FreeRTOS headers compile in C mode for a while, but I forgot to add the .c file for the test.

Add missing test file.

---

sdk/core/allocator/main.cc
sdk/core/scheduler/main.cc
sdk/core/scheduler/thread.h
sdk/core/scheduler/timer.h
sdk/core/switcher/entry.S
sdk/include/FreeRTOS-Compat/task.h
sdk/include/platform/generic-riscv/platform-timer.hh
sdk/include/thread.h
sdk/lib/debug/debug.cc
tests/locks-test.cc

Timers are now not set for a regular tick, they are set when a thread
may be preempted.  Specifically, the timer is set to the next timeout
that will trigger a scheduling operation.  This avoids timers
triggering a switch to the scheduler to do nothing (resume the currently
running thread).
This means that if a thread sleeps for ten ticks while another runs, we
will get one timer interrupt ten ticks in the future, rather than ten
interrupts one tick apart.
This means that ticks are now calculated retroactively based on elapsed
time, rather than counted on each context switch.
This, in turn, necessitates some small API changes.  We previously
conflated two things:
- Sleep for N * (tick duration)
- Yield and allow lower-priority threads to run for, at most, N * (tick
duration)
These are now …

Make the scheduler tickless

---

sdk/core/scheduler/timer.h

There are two reasons we request a timer interrupt:
- There is a peer at the same scheduler priority.
- There is a timer that will expire.
If *both* of these were true, we were delaying the scheduling until the second condition.

Fix corner case in tickless scheduling.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
sdk/core/scheduler/main.cc
sdk/include/futex.h
sdk/include/microvium/microvium_port.h
sdk/include/stdlib.h
tests/allocator-test.cc

The current `timeout` argument of `heap_allocate*` functions determines whether or not and how long the allocator should block for an allocation to be fulfiled. However it does not control on what events the allocator should block.
Currently the allocator would block for three reasons: 1) there is no heap space available anymore, 2) the quota is exhausted, and 3) the quarantine is holding back memory which could be used for the allocation.
For `malloc` and `calloc`, we only want to wait on the quarantine. Thus, we need a finer way to control this blocking behavior.
This PR implements an API to do this, and uses it for `malloc` and `calloc`.
While we are at it, it does a little bit of cleanup in futex which has similar code with `flags`, but got it wrong.

Add an API to control the blocking behavior of the allocator at a finer grain

---

sdk/include/cdefs.h
tests/test-runner.cc

This is the other half of CHERIoT-Platform/llvm-project#29
The compiler will now use the correct calling convention for `__builtin_strlen`, but does not know how to generate it as a mangled name.  We do this by hand to avoid adding more complexity to the compiler for a special case.

Fix `__builtin_strlen`

---

sdk/include/stdio.h

The Arty A7 bootloader uses some of the RTOS headers but does not define the UART in the normal way (and can't because it runs before the loader) and so this is broken.

Don't expose printf if we don't have a stdout.

---

tests/test-runner.cc
tests/tests.hh

This is improves on TEST as it automatically prints the expected and actual values.  A quick grep indicates about 200 places in the test suite this could be used.

Add TEST_EQUAL macro in tests.hh.

---

examples/08.memory_safety/memory_safety_inner.cc

Ages ago, we made store-local violations clear the tag rather than trap.

Fix the memory safety example for the non-trapping behaviour.

---

examples/08.memory_safety/README.md
examples/08.memory_safety/memory_safety_inner.cc

Update the ReadMe for example 08 to better reflect the impact of storing non global pointers in the heap/global

update ReadMe for example 08

---

sdk/include/platform/sunburst/platform-i2c.hh

I2C interrupts now properly cleared by `interrupt_clear()`.

Fix #274 (Bug in Sonata I2C header).

---

examples/04.temporal_safety/README.md
examples/04.temporal_safety/allocate.cc
examples/04.temporal_safety/claimant.cc
examples/04.temporal_safety/claimant.h
examples/04.temporal_safety/xmake.lua

Following the recent thread with Murali on sub objects I though it would be useful to add some more use cases to the temporal_safety example to illustrate sub objects and also claims

Add more examples of temporal safety

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
sdk/core/loader/boot.cc
sdk/firmware.ldscript.in
sdk/include/compartment-macros.h
sdk/lib/compartment_helpers/claim_fast.cc
sdk/xmake.lua
tests/misc-test.cc
tests/xmake.lua

This provides a mechanism to statically define globals that can be shared between compartments statically.  As with MMIO imports, these can be imported with restricted permissions.
They currently show up in the audit log as MMIO imports.  This is not ideal, we should plumb their names through into the audit log so that cheriot-audit can check that all references to a pre-shared object refer to exactly one object.
Fixes #282

Add initial support for pre-shared globals.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc

The allocator is happy with just load + capability permissions.  Without store, it can't accidentally damage hazard lists.  Without load-mutable, it can't accidentally load a writeable capability.
This is purely defence in depth.  The allocator can still write to any heap memory, so not being able to load mutable capabilities doesn't restrict what it can do.  The allocator can still ignore hazard pointers, so not being able to write them is also no reduction in ability.  It simply constrains where bugs must be.

Reduce the permissions on hazard pointers.

---

sdk/include/platform/sunburst/platform-ethernet.hh

The returned Ethernet frame was precisely bounded, but Ethernet frames can be all sorts of odd sizes and may not be representable with the capability bounds encoding.  This resulted in the tag being cleared, which caused a trap in the firewall.  The firewall is designed to fail closed, so this then prevented any further packets from arriving.
The bounding is purely defence in depth, so it's fine to use imprecise bounds here.

Fix a bug in the Sonata Ethernet driver.

---

sdk/boards/sonata-0.2.json
sdk/boards/sonata-prerelease.json
sdk/include/platform/sunburst/platform-ethernet.hh

The log packet filtering was being wrapped in a conditional and then using a template that used a different conditional, so never reported anything.  Fix this to instantiate the template properly.
Also add two defines that tell FreeRTOS+TCP the offload features that this network interface exposes.  This improves performance and reduces code size.

Sonata Ethernet driver cleanups.

---

sdk/boards/sonata-prerelease.json
sdk/include/platform/sunburst/platform-pwm.hh

This PR implements a driver for the Pulse-Width Modulation (PWM) used on the Sonata board.
Note that the linked documentation source is currently out of date - I believe that @HU90m intends to update that to reflect the actual hardware, which is what this driver is based on.
I've confirmed that this is working for the 1 PWM that we have on Sonata by implementing the following in a simple piece of firmware with a single compartment: 
```cpp
#include <compartment.h>
#include <platform-pwm.hh>
#include <thread.h>
void __cheri_compartment("pwm_test") pwm_test()
{	
auto pwm = MMIO_CAPABILITY(SonataPulseWidthModulation, pwm);
uint8_t counter = 0;
while (true) 
{
counter = (counter + 1) % 255;
pwm->output_set(0, 255, counter);
thread_millisecond_wait(50);
}
}
```
Checking with a Multimeter I can …

Implement PWM Driver for Sonata Board

---

scripts/run_clang_tidy_format.sh
sdk/include/stdalign.h
sdk/include/stdnoreturn.h
tests/ccompile-test.c

These were added in C11 and removed in C23.  The implementations are no-ops in C++ and C >= C23 modes.

Add stdalign.h and stdnoreturn.h.

---

sdk/boards/sonata-prerelease.json
sdk/include/platform/sunburst/platform-adc.hh

This PR implements an Analogue-to-Digital Converter (ADC) driver for the Sonata Board's Xilinx ADC (XADC). 
The relevant documentation can be found on the [Sonata System documentation](https://lowrisc.github.io/sonata-system/doc/ip/adc.html) and in the [XADC Specification](https://docs.amd.com/r/en-US/ug480_7Series_XADC), and is referenced in comments through the driver code.
Sonata's XADC is configured to be initialised with default values that start it in "independent ADC mode", which will by default monitor system internals and sample connected analogue channels. As a result, this driver aims to provide a very simple interface for reading these registers, as well as changing the XADC's clock speed or powering it down so that you can reduce power draw if not using the ADC. I've tried to …

Implement ADC Driver for Sonata Board

---

scripts/run_clang_tidy_format.sh
sdk/core/allocator/main.cc
sdk/core/scheduler/main.cc
sdk/core/switcher/entry.S
sdk/include/setjmp.h
sdk/include/unwind.h
tests/stack-test.cc
tests/test-runner.cc
tests/tests.hh
tests/unwind_cleanup-test.cc
tests/xmake.lua

This is two commits.  The first reserves space on the stack on each compartment transition so that you have space for per-thread per-invocation state.
The second adds some exception-like macros that are similar to Win16 SEH and OpenStep exceptions.

Add some primitive unwinding support

---

sdk/core/switcher/entry.S
sdk/include/switcher.h
tests/crash_recovery-test.cc

This lets long-running compartment invocations (for example, thread entry points) determine that they are in a known-valid state.
Fixes #299

Allow the error invocation handler count to be reset.

---

sdk/xmake.lua

By default lld will try to write a copy of the ELF PHDRs in the final memory image before the first loadable segment. Normally this is elided because there is insufficient space before the first loadable segment, but if the starting address specified for the instruction_memory (in the board JSON description) leaves sufficient space this can happen. To disable this behaviour add the -n option to the lld command line; the other effects of -n are irrelvant: no page alignment of sections (done already by the linker script), and link against static libraries.

Disable including the ELF headers in the firmware image.

---

sdk/include/cheri.hh
tests/misc-test.cc

This copies "the TLS stack buffer trick" into the base RTOS for broader use.  The implementation can be replaced with [CSetBoundsRoundDown](https://github.com/CHERIoT-Platform/cheriot-sail/pull/74) if and when that lands in the ISA.

Add a Capability::bounds().set_inexact_at_most() method

---

sdk/core/switcher/entry.S

With the most recent changes, we were exiting threads via the fault-in-the-switcher path.  The new code put the initial csp (full bounds, address 16 bytes from the top) on the first trusted-stack frame. When we tried to pop this, we were getting a bounds fault because we tried to restore two registers from the 16-byte offset for error handlers / local state, and then a third one from off the top.  This then triggered a bounds fault in the switcher and we bounced to the thread-exit path.
Prior to the most recent change, the top trusted-stack frame had a 0 csp, so we'd get a tag violation and hit the same path a couple of instructions earlier.
This was due to the fact that our bounds check was checking if the *current* trusted stack frame was the top one, not checking the previous one.  The …

Clean up the thread-exit path.

---

sdk/core/switcher/entry.S

We were spilling the trusted stack pointer to the csp slot in the thread's register save area.  This shouldn't matter because you can't resume a thread that has exited, but it's good defence in depth to not do this and spill 0 instead.

More defence in the thread unwind path.

---

sdk/core/allocator/main.cc
sdk/core/loader/boot.cc
sdk/core/scheduler/common.h
sdk/core/scheduler/main.cc
sdk/core/scheduler/multiwait.h
sdk/core/token_library/token_unseal.S
sdk/include/compartment-macros.h
sdk/include/compartment.h
sdk/include/token.h

This separates the sealing hardware sealing types used for heap-allocated objects from the sealing type used for static sealed objects.  The main goal of this was to remove the allocator from the TCB for statically sealed objects but, as a side benefit, we also delete about 200 lines of code and make the binaries around 100 bytes smaller.
We had previously reserved a type for the scheduler's sealed types to remove the allocator from the scheduler's TCB for static objects.  This is no longer required.  The allocator is in the scheduler's TCB for dynamically sealed objects (but it is anyway, because they live on the heap), but not for statically sealed objects.  This removes a load of special-case code from the scheduler.
This also means that we didn't increase the number of hardware …

Separate static and dynamic sealing types.

---

sdk/core/allocator/main.cc
sdk/core/loader/types.h
sdk/core/token_library/token_unseal.S
sdk/firmware.ldscript.in
sdk/privileged-compartment.ldscript
sdk/xmake.lua
tests/static_sealing-test.cc
tests/static_sealing.h
tests/static_sealing_inner.cc

We originally reserved one capability of space at the start of each of the core RTOS compartments for a sealing key.  Then, when we added the virtualised sealing mechanism to the allocator, this grew to two.
The allocator is the only compartment that uses both slots and, after merging #316, the scheduler doesn't use any.  This space is therefore wasted.
This commit removes this space and adds a mechanism that allows privileged compartments to reserve one or two slots.
Eventually we can probably replace this with a normal imported sealing capability, but for now this at least removes the wasted space.
This does not currently reduce code size, because replacing the inline assembly with a load of a global adds a csetbounds.  This can be fixed in the compiler independently.
While we're here, …

Remove space reserved at the start of privileged compartments.

---

examples/06.producer-consumer/producer.cc
sdk/include/FreeRTOS-Compat/queue.h
sdk/include/queue.h
sdk/lib/queue/README.md
sdk/lib/queue/queue.cc
sdk/lib/queue/queue_compartment.cc
sdk/lib/queue/xmake.lua
tests/allocator-test.cc
tests/multiwaiter-test.cc
tests/queue-test.cc

My original implementation was a bit CHERI-happy and put a lot of capabilities in each endpoint to enforce properties with a not-very-well-thought-through thread model.
The new code is simpler in a few ways:
- The queue metadata and ring buffer are a single allocation.
- The producer / consumer counters are indexed directly, not via indirection.
- We don't do permission checks and claims for defensive programming in the send and receive functions, we use the unwind error handling so don't need to enumerate possible badness.
- The library returns a pointer to the allocation directly, rather than a (large) value type and a pointer that is used for freeing.
- Restricted endpoints are just a simple indirection layer and are only in the sealed version where they might make sense with a threat …

Simplify message queues.

---

sdk/core/loader/boot.cc
sdk/core/switcher/entry.S
sdk/include/compartment.h
tests/stack-test.cc
tests/stack_integrity_thread.cc
tests/stack_tests.h

#320 is taking a while since it's a sizable amount of prose.  Pull the end-user visible changes off the bottom and make them their own PR.

Switcher fixes from #320

---

sdk/include/setjmp.h

This is specified in C / C++ standards and may enable very slightly better optitmisation. Not sure what is the most portable way to specify this but this but this seems to work.

Make longjmp noreturn.

---

sdk/core/switcher/entry.S

Having chopped the stack to its post callee-save-register spill address, csp might have fewer than STACK_ENTRY_RESERVED_SPACE bytes of length. Subtraction by that value would then make the count of available bytes, held in t2, negative.  The test, unsigned tp >= t2, thus risks misinterpreting a negative t2.
On the other side of the comparison, we have, in tp, the number of required bytes between 0 and 0x7F8 (the result of an unsigned byte load left shifted by 3).  Given this extremely limited range, we can move the subtraction of STACK_ENTRY_RESERVED_SPACE from t2 to being an addition on tp without risk of carrying into the sign bit.

switcher: correct sufficient stack space check

---

sdk/core/switcher/entry.S

- `.Lforce_unwind` and `.Lskip_compartment_call` are the only two callers of `.Lpop_trusted_stack_frame`, and they're remarkably similar, with the only difference being that the latter passes through the callee compartment's return registers and the former forces the return registers to -ECOMPARTMENTFAIL and 0.
- Having done that, `.Lpop_trusted_stack_frame` has only a single caller, so inline it.
- Then, we no longer need to preserve `cra` across its (now inlined) body, so don't.
Staged across commits for ease of review.

switcher: common up unwind paths

---

sdk/core/loader/boot.cc
sdk/core/loader/types.h
sdk/core/switcher/entry.S
sdk/firmware.ldscript.in
sdk/include/fail-simulator-on-error.h

Rather than infinitely looping such a damaged thread, request that the scheduler stop running it (via .Lset_mcause_and_exit_thread).  This should never happen, as .Lpop_trusted_stack_frame tries to exit any thread that runs out of trusted stack frames, but the scheduler could ask us to resume such a thing anyway.

switcher: change TrustedStack underflow to exit

---

sdk/core/loader/boot.cc
sdk/core/switcher/entry.S
sdk/include/cheri.h
sdk/include/cheri.hh
tests/crash_recovery-test.cc

The core change here is the addition of _two instructions_ to the switcher.  There's a change to our crash_recovery test that makes sure we're doing the right thing (and which fails when those two new instructions are not present).  And because that wanted to use a symbolic name for one number that was previously somewhat buried, there's a lot of shuffling of symbolic names for things, to hopefully make similar things easier in the future.

IRQs on in compartment fault handlers

---

tests/test-runner.cc

This technically isn't in C++20, and clang-17 starts to enforce that restriction.
It's simple to remove it in this case, and doing so allows both clang-15 and clang-17
to work on the same codebase.

Eliminate use of #elifdef

---

sdk/include/platform/sunburst/platform-usbdev.hh

Some examples of this driver's use can be found in `sonata-system`, e.g. the CI test: [`usbdev_tests.hh`](https://github.com/lowRISC/sonata-system/blob/main/sw/cheri/tests/usbdev_tests.hh).
No CHERIoT RTOS examples or utility libraries yet though I'm afraid.

sonata: Added a driver for the OpenTitan USB block

---

sdk/lib/crt/arith64.c

The compiler believes that the x25519 layer in libhydrogen has a dependency on __multi3(), even though it can generate the code fine if asked directly to multiply two uint64_t values.    So we'll humour it by giving it that as an implemenation.  
Closes #352

Add __multi3() to crt library

---

sdk/core/allocator/alloc.h
sdk/include/stdlib.h
tests/allocator-test.cc

`allocator-test.cc` needs to account for underlying object sizes.  Expose the information it needs to do so and update documentation on heap interface functions.

Allocator: expose minimum chunk size information, fix test

---

scripts/dot_from_switcher.lua
sdk/core/loader/boot.cc
sdk/core/loader/types.h
sdk/core/switcher/entry.S
sdk/core/switcher/tstack.h
sdk/firmware.ldscript.in
sdk/include/assembly-helpers.h
sdk/lib/unwind_error_handler/unwind.S
tests/crash_recovery-test.cc

The switcher is a very small, and yet also big, chunk of carefully hand-written, security-critical assembler.  In absence of formal verification of correctness, add more commentary about what's going on.
At the time of writing, this just adds "Register Atlas"es to the `__Z26compartment_switcher_entryz` entry point (and very slightly moves some code around).
I would also like to have "Control Flow Atlas"es with backwards arcs from labels with interesting control flow, but I haven't gotten there yet.
Mostly posting for bikeshedding and commentary; commit early, commit often.

WIP: various tweaks to, and a pile of documentation for, the switcher and exception handler

---

sdk/core/loader/boot.cc
sdk/core/switcher/entry.S
sdk/firmware.ldscript.in

This shrinks the switcher section by 22 bytes in total and removes 10 instructions, 6 of which were in the swticher "core" (cross-call and exception paths).
If we end up keeping the CUnseal-inbounds architectural change (https://github.com/CHERIoT-Platform/cheriot-sail/pull/87), then this is especially worthwhile, as it dodges the need to add a few csetbounds instructions.
Doing this separately from #358 because it's a hair more invasive and could stand to be reviewed independently.

switcher: use two different (un)sealing caps

---

sdk/include/string.h
sdk/lib/freestanding/compat.S
sdk/lib/freestanding/memcmp.c
sdk/lib/freestanding/memcpy.c
sdk/lib/freestanding/memset.c
sdk/lib/freestanding/xmake.lua
tests/misc-test.cc

Mangling these is painful for the compiler and we've missed at least one place where it needs to happen.  We don't mangle the atomics, so it's a good idea to also not mangle the freestanding ones.
As a transitional measure, export the functions as both their mangled and unmangled forms.
The next step is to make the mangled form the compatibility definition and use `asm` in the header to export these as non-mangled by default for direct calls, then finally to remove `compat.S`.
Once this is merged, the compiler is free to start emitting `mem*` as libcalls without name mangling.
Fixes #368

Export freestanding symbols as unmangled.

---

sdk/core/loader/boot.cc
sdk/core/loader/types.h
sdk/core/switcher/entry.S
sdk/core/switcher/export-table-assembly.h

Pulling from https://github.com/CHERIoT-Platform/cheriot-rtos/issues/334 .  This is much, much smaller than #320 and so hopefully that much easier to review.  As usual, commit-by-commit is probably the right approach.
I am only so confident in the `mscratchc` changes, as they are not mechanically checked, though the version here does run the test suite on my machine (and several nearby versions, in some sense, do not).  We might want to tear the bottom commits off this PR, as often happens.

Next round of changes to the switcher

---

sdk/core/allocator/main.cc
sdk/include/queue.h

Previously `heap_can_free` would succeed in a situation where `heap_free` would fail with an insufficient-stack error.

Improve a comment and fix heap_can_free.

---

sdk/core/scheduler/common.h
sdk/core/scheduler/main.cc
tests/multiwaiter-test.cc

The scheduler compartment offers a small menagerie of dedicated object types to the system though the (static and dynamic) software capability mechanisms.  The private internals of these objects are subtypes of the [`Handle`](https://github.com/CHERIoT-Platform/cheriot-rtos/blob/2625f2de6ddd8773c4a59ab5fb6ab5ba2d371b54/sdk/core/scheduler/common.h#L54-L91) `struct`.  `Handle`s know how to `unseal` themselves with a fair bit of paranoia, by invoking `token_obj_unseal_dynamic` or `token_obj_unseal_static` with the per-type sealing type (b9f206a7c9b138e762b51f539d085a4d7377a516 eliminated the use of a dedicated hardware sealing type for the scheduler's use in favor of the static/dynamic partition.)  The scheduler has an internal affordance making the use of `Handle`s particularly convenient: …

scheduler dynamic object deallocation must use the token APIs

---

sdk/core/scheduler/thread.h

The priority map was not updated so if the highest-priority thread exited then the next thread would not become runnable.

Fix a bug in thread exits.

---

sdk/boards/ibex-safe-simulator.json

With https://github.com/microsoft/cheriot-safe/pull/22 now getting the revoker's attempts to interrupt us through the PLIC to the core, it turns out we need to acknowledge the PLIC's attempts to poke us, or it will never do so again.
This won't matter for CI -- or, at least, its effects will not be visible -- until we rebuild the dev container with the aforementioned PR applied to its verilated Ibex(es) (Ibexen? Ibices?).

ibex: the revoker IRQ is edge-triggered

---

sdk/boards/sonata-prerelease.json
sdk/boards/sonata-simulator.json

Replay #384 for a related platform.  With this in place, I can get the revoker IRQ test to pass on the 1.0 hardware.
```
top: At startup, revocation epoch is 0x0; waiting...
top: After wait: for 0x0, result true, epoch now is 0x2, wait elapsed 0x0 remaining 0x32
top: After wait: for 0x2, result true, epoch now is 0x4, wait elapsed 0x0 remaining 0x32
top: After wait: for 0x4, result true, epoch now is 0x6, wait elapsed 0x0 remaining 0x32
top: After wait: for 0x6, result true, epoch now is 0x8, wait elapsed 0x0 remaining 0x32
top: After wait: for 0x8, result true, epoch now is 0xa, wait elapsed 0x1 remaining 0x31
top: After wait: for 0xa, result true, epoch now is 0xc, wait elapsed 0x0 remaining 0x32
top: After wait: for 0xc, result true, epoch now is 0xe, wait elapsed 0x0 remaining 0x32 …
```

sonata-prerelease: revoker IRQ is edge triggered

---

tests/allocator-test.cc

Hold on to a random collection of freed pointers (stored before we free them) and, after each round, scan the collection looking for asserted tags.  This could happen if an object is prematurely released from quarantine before the revoker gets to the copy here in the collection.

allocator-test/fuzz: stochastic necromancy test

---

scripts/generate_compile_commands.sh

Invoke env from its standard location.  If you're going to hard-code a non-standard env location to find bash, you may as well hard-code a bash location.
Generate the top-level compile_commands.json from the test suite so that syntax highlighting in the RTOS works again.

Fix bugs in generate_compiler_commands.sh

---

sdk/include/cheri-builtins.h

This file contained three things:
- The old names from CheriBSD (based on the CHERI MIPS mnemonics) wrapping the macros.
- A bunch of inline assembly functions that replicated things that we have builtins for.
- A bunch of random things that we don't use with silly names.
This commit:
- Deprecates the old CHERI MIPS names.
- Adds the modern names that match the Clang header.
- Removes a few that were never part of CHERIoT entirely (any code that used them probably crashed the compiler and definitely didn't work).
- Adds the missing ones.

Clean up cheri-builtins.h

---

sdk/include/cheri-builtins.h

It's useful to be able to use them in C/C++ headers.

Add C-style builtins as C++ static inline functions.

---

.github/workflows/test-new-xmake-nightly.yml

I, uh, fixed(?) it, in that it now runs the test we mean to be running to completion successfully, but I don't like it.
There were several things wrong:
- `xmake`'s profile script uses `source`, which `sh` doesn't (and doesn't have to) understand
- https://github.com/xmake-io/xmake/issues/6030
- Copy-paste mistake meant that we weren't passing a board JSON to `xmake config` if we got there.

fix xmake nightly

---

sdk/core/scheduler/main.cc
sdk/include/fail-simulator-on-error.h
sdk/include/simulator.h
tests/test-runner.cc

Wrap the cross-call, which can fail, in a noreturn void wrapper that can't.  Tweak callers appropriately.  Have the scheduler internally use the platform layer everywhere.
More stuff pulled out of #379 for separate review.

Tidy simulation_exit

---

sdk/boards/sonata-prerelease.json
sdk/xmake.lua

Fixes https://github.com/CHERIoT-Platform/cheriot-rtos/issues/397

Allow boards to specify CXFLAGS, and use that to disable machine outlining for Sonata.

---

sdk/boards/sonata-prerelease.json
sdk/boards/sonata-simulator.json

This is necessary because the sonata simulator has an old version of the ISA that is not compatible with outlining. It was already disabled for sonata-prerelease but the simulator was missed. We should re-enable when the sonata is upgraded.

Disable machine-outlining on sonata_simulator to fix CI.

---

sdk/core/scheduler/main.cc
sdk/core/scheduler/thread.h
sdk/core/scheduler/timer.h
sdk/include/platform/generic-riscv/platform-timer.hh

The current code yields and schedules a new thread if any equal or higher-priority thread has become runnable.
The new code decomposes these cases.  If a new thread is runnable and should run now, the current thread yields.  If a new thread is runnable but is the same priority as the current thread, the scheduler ensures that a timer interrupt is ready but does not yield immediately.
This improves the test suite performance by around 2% and a producer-consumer microbenchmark by about 35%.

Improve futex_wake behaviour.

---

sdk/core/loader/boot.cc
sdk/core/scheduler/main.cc
sdk/include/interrupt.h

- **Fix scheduler compartment name used in DECLARE_INTERRUPT_CAPABILITY.**
- **Remove 'sched' namespace in scheduler.**

Remove sched namespace in scheduler

---

scripts/includes/helper_find_llvm_install.sh
scripts/run-sonata.sh

1) In helper_find_llvm_install the error message was captured by $() so not visible, so print it to stderr instead.
2) Since set -e is on if command -v uf2conv failed the script would exit without printing an error.

Fix some error cases in run-sonata.sh.

---

scripts/run-sonata-1.0.sh
sdk/boards/sonata-prerelease.json

This is very similar to the previous script except we strip the ELF instead of using objcopy -O bin and uf2conv uses the address for fw slot1 and sets the correct magic value.
Would to also generate uf2 files for slots 2 and 3 at the same time if desired.

Add run script for sonata v1.

---

sdk/core/loader/boot.cc
sdk/core/software_revoker/revoker.cc
sdk/firmware.ldscript.in
sdk/include/platform/ibex/platform-hardware_revoker.hh
tests/allocator-test.cc

Explicitly test for revocation in all of globals, the stack, and the trusted stack.

allocator-test: probe revocation in more places

---

sdk/boards/sonata-1.0.patch
sdk/boards/sonata-1.1.json
sdk/boards/sonata-prerelease.patch
sdk/boards/sonata-simulator.patch
sdk/xmake.lua

The -prerelease name is now gone, since everything we support is currently in a release.  We can resurrect it if needed.
1.0 is defined as a small diff on 1.1 (it adds some small tweaks to handle missing features.).

Add Sonata 1.0 and 1.1 board descriptions.

---

scripts/run-sonata-1.0.sh

The script will still install in slot1, but it's useful to also have slot2 and slot3 versions available.

run-sonata-1.0.sh: build uf2 files for all firmware slots.

---

sdk/include/stdio.h
tests/stdio-test.cc

We can use the length of the output capability to calculate the length to pass to vnsprintf, making sprintf safe! Also fixes an error in the prototype for vnsprintf.

Add sprintf to stdio.

---

sdk/include/thread.h
sdk/lib/event_group/event_group.cc

While here, add a note for future users of `thread_id_get`.  At a glance, nobody else in-tree is yet indexing quite like this, and [the scheduler](https://github.com/CHERIoT-Platform/cheriot-rtos/blob/7da05da6e1f7bb517b4d0517b0f0dd4cb69a7142/sdk/core/scheduler/main.cc#L203-L210) is already doing the right thing (or we'd probably have noticed a lot sooner).
This has been lurking for a long while, at least since b5692081e26fb7ad9c0a1bde3eb059d6037d1336.

event_group: thread IDs are 1-indexed

---

.github/workflows/main.yml
scripts/run-sonata-sim.sh
sdk/core/allocator/main.cc
sdk/include/debug.hh
sdk/xmake.lua
tests/debug-test.cc
tests/stack_integrity_thread.cc
tests/test-runner.cc
tests/tests.hh

The class is now instantiated with a threshold level, from None to Error (for backwards compatibility, true means Information and false means None).
Log messages also provide a log level (Information if none is provided) and will fire if the log level is greater than or equal to the threshold.

Add support for levels in the ConditionalDebug class.

---

sdk/include/compartment-macros.h

This makes the use case of variable-sized software capabilities (flexible array member) simpler.

Allow providing an explicit type for static sealed things.

---

sdk/include/compartment-macros.h

CI is currently failing in main due to this somehow slipping through. The brackets are never actually needed because the macro will probably fail horribly if name is not a single token, but this mollifies clang-tidy.

Fix clang-tidy warnings in compartment-macros.h

---

sdk/include/platform/sunburst/v0.2/platform-gpio.hh

This was introduced when merging https://github.com/CHERIoT-Platform/cheriot-rtos/pull/437 but noone noticed because we have no CI for sonata 0.2 and everyone migrated to 1.0.

Fix compilation error in Sonata 0.2 GPIO driver.

---

sdk/xmake.lua

Otherwise, for example, building our network stack's MQTT compartment with debugging will get some of its printf()s replaced with putchar() and puts(), which we don't have.

Pass -fno-builtin-printf, too

---

sdk/include/token.h

Expose `token_unseal` as the type-safe wrapper for everything (C macro, C++ templated function).  Make `token_allocate` not use the `Sealed` wrapper when it's not needed.
The macro currently triggers a compiler bug.

Small improvements to the token APIs.

---

sdk/include/compartment-macros.h
tests.extra/regress-double_ref_shared/README.md
tests.extra/regress-double_ref_shared/common.h
tests.extra/regress-double_ref_shared/top1.cc
tests.extra/regress-double_ref_shared/top2.cc
tests.extra/regress-double_ref_shared/xmake.lua

This currently fails to link with...
```
/cheri/out/cheriot/sdk/bin/ld.lld -n --script=../../../../../build/cheriot/cheriot-rtos/regress-double/build.sonata/top_compartment-firmware.ldscript --relax -o ../../../../../build/cheriot/cheriot-rtos/regress-double/build.sonata/cheriot/cheriot/release/top_compartment --compartment-report=../../../../../build/cheriot/cheriot-rtos/regress-double/build.sonata/cheriot/cheriot/release/top_compartment.json ../../../../../build/cheriot/cheriot-rtos/regress-double/build.sonata/.objs/cheriot.loader/cheriot/cheriot/release/__/__/sdk/core/loader/boot.S.o ../../../../../build/cheriot/cheriot-rtos/regress-double/build.sonata/.objs/cheriot.loader/cheriot/cheriot/release/__/__/sdk/core/loader/boot.cc.o …
```

tests.extra/regress-double_ref_shared

---

sdk/include/debug.hh
tests/test-runner.cc

This requires a reinterpret_cast rather than a static cast.

Enable printing function pointers using debug::log.

---

sdk/core/scheduler/main.cc
sdk/include/c++-config/atomic
sdk/include/futex.h
tests/futex-test.cc

The scheduler doesn't require store permission for futexes when it does futex_wake, so don't require any permissions here.  This means that you can spuriously wake any thread waiting on a futex that you have any pointer to, even a read-only one, but the API permits spurious wakes.
The benefit from this is that the scheduler cannot tamper with a futex word.  For example, if a futex is a trivial lock where 1 indicates locked and 0 indicates unlocked, the scheduler currently can both wake waiters and set the lock value to 0 making two threads believe that they acquired the same lock.  With this change, an attacker who gets arbitrary code execution in the scheduler cannot do this, they can only cause threads to wake, see that the lock is already acquired, and then go back to sleep.
The C++ …

Reduce scheduler permissions slightly.

---

sdk/include/compartment-macros.h

This seems to work around a linker bug

Weak, not comdat, sealed object import table entries

---

sdk/include/platform/sunburst/platform-adc.hh
sdk/include/platform/sunburst/platform-i2c.hh

Debug flag should probably be consistent among drivers and should probably default to being off

sunburst: default to debug being switched off

---

sdk/boards/ibex-arty-a7-100.patch

Fix incorrect path for kunyan_ethernet device in arty-a7 board patch.

---

sdk/core/loader/boot.cc
sdk/core/switcher/entry.S
tests/misc-test.cc
tests/test-runner.cc

Since the switcher does not load any globals via PCC it does not need
the Global permission on its PCC.  Removing it slightly reduces its
privilege and also means the return sentry that compartments get is
local, slightly reducing the scope for mischief.

Remove global permission from switcher PCC.

---

examples/02.hello_compartment/hello.cc

Don't use the UART in the hello compartment (example 2).

---

benchmarks/interrupt-latency-ext/interrupt_bench.cc
benchmarks/interrupt-latency-ext/xmake.lua
benchmarks/timing.h
sdk/core/allocator/revoker.h
sdk/include/platform/concepts/hardware_revoker.hh
sdk/include/platform/ibex/platform-hardware_revoker.hh

This uses existing peripherals that can be used as IRQ "loopbacks",
which fire some appreciable delay after a software event, to measure
cycle, instruction, or HPMC counters of interest.  Presently, the Ibex
revoker engine or the Sunburst UART1 can be used as triggers; it should
be easy to add other sources.

New external IRQ latency benchmark

---

benchmarks/allocation/alloc.cc
benchmarks/allocation/xmake.lua

A slightly more detailed allocator benchmark, reporting more than just powers of two, and automagically sensitive to the maximum heap size.
It may not be worth running the larger size / few allocation benchmarks repeatedly, given the low variance observed in practice, but it seemed like a good idea at the time.
On my Sonata, this yields
```
#board	size	nalloc	inheap	time
sonata-1.0	32	30928	3866	332138707
sonata-1.0	64	15464	1933	174724776
sonata-1.0	128	7732	966	88808861
sonata-1.0	256	3866	483	45719597
sonata-1.0	512	1933	241	23773772
sonata-1.0	1024	966	120	12904387
sonata-1.0	2048	483	60	7308696
sonata-1.0	4096	241	30	4912352
sonata-1.0	8192	120	15	3298963
sonata-1.0	16384	60	7	2357563
sonata-1.0	32768	30	3	2172523
sonata-1.0	32768	30	3	2175256
sonata-1.0	32768	30	3	2169798
sonata-1.0 …
```

bechmarks/allocation: rework

---

sdk/include/platform/sunburst/platform-i2c.hh
sdk/include/platform/sunburst/platform-rgbctrl.hh
sdk/include/platform/sunburst/platform-uart.hh

Some memory mapped drivers were missing necessary set up to prevent an accidental copy or move.

sunburst: enforce NoCopyNoMove on MMIO drivers

---

.github/workflows/main.yml
sdk/boards/sonata-1.x-sram-mixin.json
sdk/xmake.lua

Mixins are "baseless" patches, or just a list of JSON patch directives.
Add an example to remove the use of HyperRAM on Sonata 1.x builds, removing the `"data_memory"` key and moving the `"instruction_memory"` map's values to those of SRAM.

sdk/xmake: support board mixins

---

compile_flags.txt
sdk/core/allocator/alloc.h
sdk/include/debug.hh

Prevent automagic conversion of DebugLevel to a boolean, because DebugLevel::None is nonzero (in fact, the largest of the DebugLevel values) as it is meant to be used as a threshold for reporting.
The use of an 'enum struct' means that we can't mistakenly write things like "if constexpr (DEBUG...)" and end up with debug code compiled in when DEBUG... is DebugLevel::None (or wonder why debugging might be elided when it's ::Information).
Update the sole user of DebugLevel, the allocator, to compile.

debug.hh: use 'enum struct DebugLevel'

---

benchmarks/interrupt-latency-ext/interrupt_bench.cc

Running in Verilated CHERIoT-SAFE, the revoker can take over a simulated second to complete a run, so be prepared to wait longer.  This probably could be tuned, but lowering the amount of work done too much threatens to make Sonata not actually wait for an IRQ.

irq-ext bench: wait longer for IRQs

---

sdk/core/scheduler/main.cc
sdk/core/scheduler/plic.h
sdk/include/platform/ibex/platform-hardware_revoker.hh

It's probably fine to pass around unbounded results internally, but we should certainly not do so across the compartment boundary.

scheduler: bound interrupt_futex_get

---

sdk/include/platform/sunburst/platform-ethernet.hh
sdk/include/platform/sunburst/v0.2/platform-ethernet.hh

See Table 4-35 (p. 47) of the datasheet for the KSZ8851SNL/SNLI (KSZ8851 SPI Ethernet MAC) used on Sonata.
The ICMP Checksum Generation field should be the 8th (zero-indexed) bit of the Transmit Control register, not the 9th. This means that with the current Ethernet driver, ICMP checksums are not being generated by Sonata, which is not intended.

Sunburst: Fix Ethernet ICMP checksum field offset

---

sdk/include/FreeRTOS-Compat/FreeRTOS.h
sdk/include/FreeRTOS-Compat/stream_buffer.h
sdk/include/queue.h
sdk/lib/queue/queue.cc
sdk/lib/queue/queue_compartment.cc
tests/queue-test.cc

The core of this is a pair of APIs for sending and receiving more than one element to a queue in a single call.  These are also exposed for the queue compartment, which lets you amortise the cost of cross-compartment calls.
A stream is a message queue where queue items are one byte long. Sending multiple queue items at a time gives a byte-stream abstraction.
FreeRTOS streams are a bit more complicated than CHERIoT RTOS version and have explicit thresholds and callbacks.  These are approximated here.

Add a stream implementation and most of the FreeRTOS compat API.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/alloc_config.h

Centralize the comparison between a C preprocessor macro and an enum value.  This eliminates many -Wtautological-compare warnings.
Bug fix on 59c2e7a03cd4633f689b106e51875c86ea2386e5

alloc: suppress debug level warnings

---

scripts/includes/helper_find_llvm_install.sh

For required tools, it's fine not to have the actual file name, so long as the thing we have is something the shell understands as a command when run.

helper_find_llvm_install: $PATH suffices

---

tests/stack_integrity_thread.cc

- We weren't declaring "ca1" as clobbered, but it is as part of the switcher returning -ECOMPARTMENTFAIL and zeroing the 2nd return register.  The control flow here is a little dizzying:
1. the `cjalr ct2` in `exhaust_thread_stack_spill`, vectors to
2. the switcher's `__Z26compartment_switcher_entryz`, which reaches
3. `.Lswitch_entry_first_spill` and traps (bounds violation on `csp`), causing the core to install mtcc as pcc, taking us to
4. `exception_entry_asm`, which eventually reaches
5. `.Lhandle_error_in_switcher`, which sets `a0` to `-ENOTENOUGHSTACK` and zeros `a1`, before continuing on to
6. `.Lhandle_return_context_install`, which updates the to-be-restored `ca0` and `ca1` with those values, sets the context continuation to `.Lswitch_just_return`, and then jumps to
7. …

tests/stack_integrity: correct asm clobbers

---

sdk/xmake.lua

This will be needed to ensure that everything links properly once we
start setting EF_CHERIOT in ELF headers.

Switch to using riscv32cheriot as the default arch name when building.

---

sdk/include/platform/sunburst/platform-uart.hh

Have OpenTitanUart::init() preserve non-baud-rate bits in `control` so that things like parity() and loopback() can be set before bringing the transceivers online.  While here, add disable() to turn them off.

sunburst/uart: allow pre-init() configuration

---

sdk/include/debug.hh
tests/debug-test.cc

In particular, add a lambda-taking form like ::Assert() to help the compiler eliminate useless logging code that's below the current threshold.

debug.hh: add convenience log_if helpers & tests

---

sdk/core/loader/boot.S
sdk/core/loader/constants.h
sdk/include/priv/riscv.h

NFCI, just doing away with some magic numbers

core/loader: used named values for mie and mstatus

---

sdk/xmake.lua

Passes locally, wonder what CI thinks.  I think I'd like to have "deducing this" in some code I'm working on, so...

sdk/xmake: bump to --std=c++23

---

.github/workflows/main.yml
sdk/core/loader/boot.cc
sdk/xmake.lua

This is a long-standing todo, but it's helpful for shrinking some of our `tests.extra` unit tests, even if the full test suite would absolutely not be happy.

sdk/xmake: conditionally link the allocator

---

.github/workflows/main.yml

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks says
> When a job fails, any jobs that depend on the failed job are skipped and do not report a failure. A pull request that requires the check may not be blocked.
Which is _vexing_.  https://github.com/actions/runner/issues/2566 suggests there isn't a particularly great solution to this problem, so here's my stab at it: run `all-checks` `always()` and check that all `needs`-ed jobs have had `"success"` for their `.result`.  We can't do the requisite transforms in GH's action language, so push it over to `jq` via the shell.

GitHub CI: Don't skip `all-tests`

---

sdk/core/loader/boot.cc
sdk/core/loader/types.h
sdk/firmware.rwdata.ldscript.in
sdk/xmake.lua
tests/bigdata-test.cc
tests/misc-test.cc
tests/test-runner.cc
tests/tests.hh
tests/xmake.lua

We store the size of globals as a shifted value, which extends the maximum size of globals in a compartment from 64 KiB to 256 KiB.
This adds two new tests.  One is added to the misc test and just checks that we correctly handle globals that are larger than the range of a csetbounds with an immediate offset.
The second checks that much larger globals work.  This test is disabled because it uses so much RAM that we don't have enough for the allocator tests.
At some point, we should refactor the test suite to allow subsets of the test suite to be built.
Add test for large objects.
Fixes #230

Allow cgp to be larger.

---

sdk/include/platform/concepts/uart.hh
sdk/include/platform/generic-riscv/platform-uart.hh
sdk/include/platform/sunburst/platform-uart.hh

Since the sunburst UART is not a 16550, it can now avoid #include_next

platforms: move IsUart concept to concepts/uart.hh

---

sdk/include/debug.hh

When there are no arguments, pass a null pointer instead of materialising a zero-length array on the stack.
This reduces the test suite size by 0.1%, but also makes evaluation of the frequency of csetbounds instructions with immediate offsets less silly.

Slightly improve debug log code generation.
