scripts/devcontainer/Dockerfile

A few bugs have been fixed upstream specifically to help us, so we should probably take advantage of the fixes.

Update xmake to the latest version in the Dockerfile.

---

README.md

Based on Ben Laurie's feedback.

Make the dependency installation instructions clearer.

---

sdk/core/scheduler/main.cc

These don't touch any scheduler data structures, so can happily be preempted.

Enable interrupts for create functions in the scheduler.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc

Fix a corner case bug and fold in @JerryHsia-MS's clever tweak to quarantine handling.

Small changes to the heap allocator

---

sdk/core/allocator/revoker.h

Update the shadow bitmap in bulk, rather than with for-loops.  Running the test suite in sail shows ~7% speedup:
Before:
Test runner: Allocator finished in 6771859 cycles
Test runner: All tests finished in 7172781 cycles
After:
Test runner: Allocator finished in 6251099 cycles
Test runner: All tests finished in 6650597 cycles

revoker: Who doesn't love bit twiddling

---

sdk/core/loader/boot.cc
sdk/core/scheduler/common.h

This should allow the scheduler to export sealing types, which can then be used without the allocator to authorise scheduler operations.  There are no consumers of this yet, but eventually it should be used for statically defining event channel endpoints, especially the ones coupled to interrupt sources, so that we can statically audit who can monitor interrupts.

Initial plumbing for scheduler capabilities.

---

sdk/include/cheri.hh

Brings us into conformance with the specification and the model. See https://github.com/microsoft/cheriot-sail/blob/19ad1e982c0f876bbb3f21f39b3cee6935278adc/src/cheri_cap_common.sail#L509-L510

cheri.hh: fix Seal and Unseal

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
sdk/include/ds/ring_buffer.h

As mentioned in #106.  While here, update some commentary.

Allocator: async revoker sleep on eldest quarantined epoch

---

sdk/include/cheri.hh

By construction anything with global permission must not be derived from the stack, so we can skip that check when the caller of check_pointer requires global.

Don't check of global capabilities overlap the stack.

---

scripts/run_clang_tidy_format.sh
sdk/include/FreeRTOS-Compat/FreeRTOS.h
sdk/include/FreeRTOS-Compat/event_groups.h
sdk/include/FreeRTOS-Compat/queue.h
sdk/include/FreeRTOS-Compat/semphr.h
sdk/include/FreeRTOS-Compat/task.h

This is sufficient to build FreeRTOS+TCP.

Add FreeRTOS compat layer.

---

sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
tests/allocator-test.cc

This is discussed in some detail in #131

Exclude sealed objects from `heap_free_all`.

---

sdk/include/platform/arty-a7/platform-ethernet.hh

The Arty A7 Ethernet driver had a somewhat peculiar bug.
The firewall calls, in a loop, `receive_frame`, followed by `receive_interrupt_complete`.
Until now, the implementation of `receive_frame` only checked the current receive buffer (`BufferID::Ping` *or* `BufferID::Pong`) if that buffer was not in use.  If no packets were present on that buffer, `receive_frame` returned `std::nullopt` without checking the other buffer.
On the other hand, the implementation of `receive_interrupt_complete` checked both `BufferID::Ping` and `BufferID::Pong`. If either had packets, it returned without sleeping.
This means that, in a setting where, e.g., both `BufferID::Ping` and `BufferID::Pong` are unused, but only `BufferID::Pong` has a packet, the firewall could run into an infinite loop of checking …

Fix recv buffer bug in the Arty A7 Ethernet driver.

---

sdk/include/platform/arty-a7/platform-gpio.hh

It is very useful to know which LEDs the driver commands. Also mention the buttons and switches.

Clarify GPIO driver description.

---

.github/workflows/main.yml

This should let us use merge queues, which will save some of the pain of waiting for CI to run before being able to press buttons.

Add CI support for merge queues.

---

docs/GettingStarted.md

Update running on Arty A7 instructions to highlight clock speed information

Added clock speed information for Running on Arty A7 getting started guide

---

sdk/include/platform/sunburst/platform-i2c.hh

This has been tested with the examples in https://github.com/lowRISC/sonata-software

Added an OpenTitan I2C driver

---

sdk/include/ctype.h

https://en.cppreference.com/w/c/string/byte/isprint

Added C standard `isprint()` function

---

sdk/lib/queue/queue.cc

If a queue is full / empty and the end that can fix that is locked, we were not sleeping in the push / pop calls.

Sleep better with queues.

---

sdk/include/platform/sunburst/platform-ethernet.hh

The network stack expects to be able to receive frames in one thread and send them from another.  The Sonata Ethernet has some MMIO state that is shared between the two.
This is not a complete fix because other SPI devices can also be interleaved.  We see this sometimes when packets end up written into the LCD display.

Fix atomicity of Sonata ethernet driver.

---

sdk/include/cheri.hh
tests/misc-test.cc

- Don't take bounds by reference (rely on the caller to get the resulting length afterwards) for consistency with the other APIs here.
- We were not falling into the bit-twiddling path in the case that the length could not fit in a mantissa, and so could return an untagged result.  Instead of trying to do all the requisite logic to see if setting bounds would succeed, just try to set the bounds and see if it worked.
- Update tests to reflect new interface, and add another that would have caught the above bug.
- Move the bit math out to a separate function, giving the compiler some more flexibility in inlining.

Capability.bounds().set_inexact_at_most() fixes

---

sdk/include/cdefs.h

This should allow the freestanding headers from CHERIoT RTOS to be used for bare-metal compilation.

Make the headers more bare-metal friendly.

---

sdk/xmake.lua

Don't depend on a newer C++ than our current clang supports.

Fix the build.

---

sdk/core/allocator/token.h
sdk/core/token_library/token_unseal.S

Shave two instructions off the fast unsealer.  It's helpful to remember the ISA. :)

token_unseal: use cgettop

---

sdk/core/loader/boot.cc
sdk/core/token_library/token_unseal.S
sdk/privileged-compartment.ldscript

Merge only if https://github.com/CHERIoT-Platform/cheriot-sail/pull/87 is not reverted.

token_unseal: wield three unsealing authorities (& some tidying)

---

sdk/boards/ibex-safe-simulator.json
sdk/boards/sail.json
sdk/core/scheduler/main.cc
sdk/include/platform/generic-riscv/platform-simulation_exit.hh
sdk/include/platform/ibex/platform-simulation_exit.hh

Move platform-specific bits out to platform headers as with other drivers.

Refactor simulation exit code

---

sdk/core/allocator/alloc.h

While investigating #375, I found that the allocator occasionally double-counts free space.  The data structure is otherwise fine, but this probably means we eventually start telling clients that things could succeed when they can't.
The fix is to move the onus of free space accounting to the callers of `mspace_free_internal`, which know whether they're returning memory already accounted as allocated, quarantined, or free.

allocator: fix free space accounting

---

scripts/run_clang_tidy_format.sh
tests.extra/regress-thread_exit_IRQ/helper.cc
tests.extra/regress-thread_exit_IRQ/helper.h
tests.extra/regress-thread_exit_IRQ/top.cc

and apply the resulting formatting fixes.

Add tests.extra to directory list in run_clang_tidy_format.sh

---

.github/workflows/main.yml
sdk/core/allocator/alloc.h
sdk/core/allocator/main.cc
sdk/include/debug.hh
sdk/include/stdlib.h
sdk/xmake.lua
tests/allocator-test.cc

This has been kicking around locally and undergoing the occasional modification, but it might be useful to push into the tree even if we never use it in most cases?

Heap render debugging facility

---

sdk/core/allocator/main.cc
tests/allocator-test.cc

This includes commits from #375, which I'd like to leave open since A) it's not mine and B) it discusses what may be additional issues not addressed by these commits.

Allocator test tweaks

---

sdk/core/switcher/entry.S
sdk/include/locks.h
sdk/include/platform/sunburst/v0.2/platform-ethernet.hh
sdk/lib/compartment_helpers/README.md

Cleanup vestigal references to heap_claim_fast.

---

tests/ccompile-test.c

This is a regression test for https://github.com/CHERIoT-Platform/llvm-project/issues/118 .

Add test for compilation of setjmp / longjmp in C file.

---

sdk/core/loader/boot.cc
tests/test-runner.cc

interrupts-disabled.
Fixes #129

Disable interrupts if a thread's entry point is marked as

---

.github/workflows/main.yml

Shamelessly stolen from Matt Parkinson

GitHub CI: cancel PR workflows on new push

---

sdk/xmake.lua

Embarrassing; bug fix on 4dede83ac24caf43815b6aafc69a1bfe527d047e

sdk/xmake: fix thread priority repacking

---

sdk/xmake.lua

- Move JSON utility functions out to top-level; embarrasing bugfix on 1e3f0b42107bf7be1700f8183c0adec04fd6a4b9
- Correct the implementation of isarray() to comply with Lua's specification.  (In particular, iteration order is not guaranteed to be integer successor, even on tables that happen to be arrays.)

sdk/xmake: JSON handling fixes

---

tests/allocator-test.cc

I don't think we were previously testing that this worked.  It does, because `heap_free()` very quickly moves from using the pointer to using its cursor and internal pointers, but just to be sure...

allocator-test: pass non-GLobal pointer to free

---

compile_flags.txt

compile_flags.txt: use std=c++23

---

compile_flags.txt
docs/faq.md
sdk/xmake.lua

Subsumes #566 and uses the baremetal ABI for the loader.  @resistor ACKed these patches over there, so I'm going to push to the merge queue if CI is happy.

Loader baremetal toolchain
